#spring.elasticsearch.jest.uris=http://192.168.19.215:9200
server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://192.168.19.215:9200
  rabbitmq:
    host: 192.168.19.215
    virtual-host: /erdong
    username: erdong
    password: erdong