server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.19.215
  rabbitmq:
    username: erdong
    password: erdong
    host: 192.168.19.215
    virtual-host: /erdong
auth:
  jwt:
    publicKeyPath: D:\Idea_Workspace_my_gmall\gmall-0615\tmp\\rsa.pub
    cookieName: GMALL_TOKEN